DROP TABLE IF EXISTS APPLICATION CASCADE;

CREATE TABLE APPLICATION
(
    ID   BIGINT IDENTITY PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR2(50) NOT NULL,
    UNIQUE (NAME)
);

DROP TABLE IF EXISTS REVIEW;

CREATE TABLE REVIEW
(
    ID          BIGINT IDENTITY PRIMARY KEY AUTO_INCREMENT,
    APP_ID      BIGINT,
    RATING      DOUBLE,
    DESCRIPTION TEXT,
    UNIQUE (ID),
    FOREIGN KEY (APP_ID) REFERENCES APPLICATION (ID)
);