GET http://localhost:8080/scope

###

# set JSESSIONID from previous request to get value from the same UserSettings bean
GET http://localhost:8080/scope
Cookie: JSESSIONID=603C18FC5075BB99644ECB5739251144

###